export function exportJSON(fields, fileName) {
  const data = {
    exportedAt: new Date().toISOString(),
    source: fileName,
    totalFields: fields.length,
    avgQuality: Math.round(fields.reduce((s, f) => s + (f.qualityScore || 0), 0) / fields.length),
    fields: fields.map((f) => ({
      fieldName: f.fieldName,
      dataType: f.detectedType,
      description: f.description,
      businessCategory: f.businessCategory,
      qualityScore: f.qualityScore,
      confidence: f.confidence,
      status: f.status,
      isPrimaryKey: f.isPrimaryKey,
      isForeignKey: f.isForeignKey,
      patterns: f.patterns,
      nullRate: f.nullRate,
      uniqueRate: f.uniqueRate,
      uniqueCount: f.uniqueCount,
      sampleValues: f.sampleValues,
      issues: f.issues,
      hasPII: f.hasPII,
      piiType: f.piiType,
      piiRiskLevel: f.piiRiskLevel,
      gdprCategory: f.gdprCategory,
    })),
  };

  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${fileName?.replace(/\.[^/.]+$/, "") || "dictionary"}_datasense.json`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportMarkdown(fields, fileName) {
  const avgQuality = Math.round(fields.reduce((s, f) => s + (f.qualityScore || 0), 0) / fields.length);
  const approved = fields.filter((f) => f.status === "approved").length;
  const piiCount = fields.filter((f) => f.hasPII).length;

  let md = `# Data Dictionary — ${fileName || "Dataset"}\n\n`;
  md += `> Generated by DataSense AI on ${new Date().toLocaleDateString()}\n\n`;
  md += `## Summary\n\n`;
  md += `| Metric | Value |\n|--------|-------|\n`;
  md += `| Total Fields | ${fields.length} |\n`;
  md += `| Avg Quality Score | ${avgQuality}% |\n`;
  md += `| Approved Fields | ${approved} |\n`;
  md += `| PII Fields | ${piiCount} |\n\n`;
  md += `## Fields\n\n`;
  md += `| Field Name | Type | Description | Quality | Status |\n`;
  md += `|------------|------|-------------|---------|--------|\n`;

  fields.forEach((f) => {
    const desc = (f.description || "—").replace(/\|/g, "\\|");
    md += `| \`${f.fieldName}\` | ${f.detectedType} | ${desc} | ${f.qualityScore}% | ${f.status} |\n`;
  });

  md += `\n## Field Details\n\n`;
  fields.forEach((f) => {
    md += `### \`${f.fieldName}\`\n\n`;
    md += `- **Type**: ${f.detectedType}\n`;
    md += `- **Description**: ${f.description || "—"}\n`;
    md += `- **Business Category**: ${f.businessCategory || "—"}\n`;
    md += `- **Quality Score**: ${f.qualityScore}%\n`;
    md += `- **Confidence**: ${f.confidence}%\n`;
    md += `- **Null Rate**: ${f.nullRate}%\n`;
    md += `- **Unique Rate**: ${f.uniqueRate}%\n`;
    if (f.isPrimaryKey) md += `- **Primary Key**: Yes\n`;
    if (f.isForeignKey) md += `- **Foreign Key**: Yes\n`;
    if (f.hasPII) md += `- **PII**: ${f.piiDescription} (${f.gdprCategory}) — Risk: ${f.piiRiskLevel}\n`;
    if (f.patterns?.length > 0) md += `- **Patterns**: ${f.patterns.join(", ")}\n`;
    if (f.issues?.length > 0) md += `- **Issues**: ${f.issues.join(", ")}\n`;
    md += `- **Sample Values**: ${f.sampleValues?.slice(0, 3).join(", ") || "—"}\n\n`;
  });

  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${fileName?.replace(/\.[^/.]+$/, "") || "dictionary"}_datasense.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportPDF(fields, fileName) {
  const avgQuality = Math.round(fields.reduce((s, f) => s + (f.qualityScore || 0), 0) / fields.length);

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Data Dictionary — ${fileName}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; background: #fff; color: #1e293b; padding: 40px; }
  .header { background: linear-gradient(135deg, #6366f1, #8b5cf6); color: white; border-radius: 16px; padding: 32px; margin-bottom: 32px; }
  .header h1 { font-size: 28px; font-weight: 800; margin-bottom: 8px; }
  .header p { opacity: 0.85; font-size: 14px; }
  .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 32px; }
  .stat { background: #f8fafc; border-radius: 12px; padding: 20px; border: 1px solid #e2e8f0; text-align: center; }
  .stat .val { font-size: 28px; font-weight: 800; color: #6366f1; }
  .stat .lbl { font-size: 12px; color: #64748b; margin-top: 4px; }
  table { width: 100%; background: white; border-radius: 12px; overflow: hidden; border-collapse: collapse; border: 1px solid #e2e8f0; margin-bottom: 32px; }
  th { background: #f1f5f9; padding: 12px 16px; text-align: left; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b; }
  td { padding: 12px 16px; font-size: 13px; border-top: 1px solid #f1f5f9; }
  .badge { display: inline-flex; padding: 2px 8px; border-radius: 6px; font-size: 11px; font-weight: 600; }
  .status-approved { background: #dcfce7; color: #166534; }
  .status-pending  { background: #fef9c3; color: #854d0e; }
  .status-rejected { background: #fee2e2; color: #991b1b; }
  .quality { display: flex; align-items: center; gap: 8px; }
  .bar { width: 60px; height: 6px; background: #e2e8f0; border-radius: 3px; overflow: hidden; }
  .bar-fill { height: 100%; border-radius: 3px; }
  footer { text-align: center; color: #94a3b8; font-size: 12px; margin-top: 40px; }
  @media print {
    body { padding: 20px; }
    .header { break-inside: avoid; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .stats { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .badge { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .bar-fill { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  }
</style>
</head>
<body>
  <div class="header">
    <h1>📊 ${fileName?.replace(/\.[^/.]+$/, "") || "Data"} Dictionary</h1>
    <p>Generated by DataSense AI · ${new Date().toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" })}</p>
  </div>
  <div class="stats">
    <div class="stat"><div class="val">${fields.length}</div><div class="lbl">Total Fields</div></div>
    <div class="stat"><div class="val">${avgQuality}%</div><div class="lbl">Avg Quality</div></div>
    <div class="stat"><div class="val">${fields.filter(f=>f.status==="approved").length}</div><div class="lbl">Approved</div></div>
    <div class="stat"><div class="val">${fields.filter(f=>f.issues?.length>0).length}</div><div class="lbl">With Issues</div></div>
  </div>
  <table>
    <thead>
      <tr><th>Field Name</th><th>Type</th><th>Description</th><th>Quality</th><th>Status</th><th>Issues</th></tr>
    </thead>
    <tbody>
      ${fields.map((f) => {
        const qColor = f.qualityScore>=85?"#22c55e":f.qualityScore>=70?"#f59e0b":"#ef4444";
        return `<tr>
          <td><code style="color:#6366f1;font-weight:600">${f.fieldName}</code>${f.isPrimaryKey ? " 🔑" : ""}${f.isForeignKey ? " 🔗" : ""}${f.hasPII ? ' <span style="background:#fee2e2;color:#991b1b;padding:1px 5px;border-radius:4px;font-size:10px;font-weight:700">PII</span>' : ""}</td>
          <td>${f.detectedType}</td>
          <td style="max-width:250px;color:#475569">${f.description || "—"}</td>
          <td><div class="quality"><div class="bar"><div class="bar-fill" style="width:${f.qualityScore}%;background:${qColor}"></div></div><span style="color:${qColor};font-weight:700;font-size:12px">${f.qualityScore}%</span></div></td>
          <td><span class="badge status-${f.status}">${f.status}</span></td>
          <td style="font-size:11px;color:${f.issues?.length>0?"#ef4444":"#22c55e"}">${f.issues?.length>0?"⚠ "+f.issues.join(", "):"✓ Clean"}</td>
        </tr>`;
      }).join("")}
    </tbody>
  </table>
  <footer>DataSense AI · Multi-Agent Data Dictionary Generator · Powered by Atlas, Sage & Guardian</footer>
  <script>window.onload = () => { window.print(); window.onafterprint = () => window.close(); }</script>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  window.open(url, "_blank");
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}